name: Build Sinum iOS

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build dylib
        run: |
          cd iOS
          chmod +x build-mac.sh
          ./build-mac.sh

      - name: Upload dylib artifact
        uses: actions/upload-artifact@v4
        with:
          name: libSinum
          path: iOS/build/libSinum.dylib
