name: Build Sinum iOS

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x iOS/build-mac.sh

      - name: Run build
        run: |
          cd iOS
          ./build-mac.sh
